import {
  Tag,
  ShoppingBag,
  Film,
  Music,
  Home,
  Car,
  Utensils,
  Briefcase,
  Heart,
  Plane,
  Gift,
  Smartphone,
  Zap,
  Book,
  Dumbbell,
  Coffee,
  TrendingUp,
  PiggyBank,
  ArrowLeftRight,
  DollarSign,
} from 'lucide-react'

export const CATEGORY_ICONS = {
  tag: Tag,
  'shopping-bag': ShoppingBag,
  film: Film,
  music: Music,
  home: Home,
  car: Car,
  utensils: Utensils,
  briefcase: Briefcase,
  heart: Heart,
  plane: Plane,
  gift: Gift,
  smartphone: Smartphone,
  zap: Zap,
  book: Book,
  dumbbell: Dumbbell,
  coffee: Coffee,
  'trending-up': TrendingUp,
  'piggy-bank': PiggyBank,
  'arrow-left-right': ArrowLeftRight,
  'dollar-sign': DollarSign,
}

export const CATEGORY_ICON_OPTIONS = [
  { value: 'tag', label: 'Etiqueta' },
  { value: 'shopping-bag', label: 'Compras' },
  { value: 'utensils', label: 'Comida' },
  { value: 'coffee', label: 'Café' },
  { value: 'home', label: 'Casa' },
  { value: 'car', label: 'Carro' },
  { value: 'film', label: 'Cinema' },
  { value: 'music', label: 'Música' },
  { value: 'briefcase', label: 'Trabalho' },
  { value: 'heart', label: 'Saúde' },
  { value: 'plane', label: 'Viagem' },
  { value: 'gift', label: 'Presente' },
  { value: 'smartphone', label: 'Telemóvel' },
  { value: 'zap', label: 'Energia' },
  { value: 'book', label: 'Educação' },
  { value: 'dumbbell', label: 'Desporto' },
  { value: 'trending-up', label: 'Investimento' },
  { value: 'piggy-bank', label: 'Poupança' },
  { value: 'arrow-left-right', label: 'Transferência' },
  { value: 'dollar-sign', label: 'Salário' },
]

export function getCategoryIcon(iconName) {
  return CATEGORY_ICONS[iconName] || Tag
}
